import enum

from utils.constants.urls import (
    GET_MEASUREMENTS_BY_SENSOR_ID_DAYS,
    GET_MEASUREMENTS_BY_SENSOR_ID_MONTHS,
    GET_MEASUREMENTS_BY_SENSOR_ID_YEARS,
    WQAPI_REAL_TIME_CITY,
    WQAPI_REAL_TIME_CORDS,
    WQAPI_REAL_TIME_CORDS_RANGE,
    WQAPI_REAL_TIME_IP,
)


class Measurements(enum.Enum):
    DAYS = GET_MEASUREMENTS_BY_SENSOR_ID_DAYS
    MONTHS = GET_MEASUREMENTS_BY_SENSOR_ID_MONTHS
    YEARS = GET_MEASUREMENTS_BY_SENSOR_ID_YEARS


class RealTimeAQI(enum.Enum):
    IP_BASED = WQAPI_REAL_TIME_IP
    CITY_BASED = WQAPI_REAL_TIME_CITY
    LAT_LONG = WQAPI_REAL_TIME_CORDS
    LAT_LONG_RANGE = WQAPI_REAL_TIME_CORDS_RANGE


class Stats(enum.Enum):
    AVERAGE = "avg"
    MINIMUM = "min"
    MAXIMUM = "max"
